apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicea.fullname" . }}
  labels:
    {{- include "servicea.labels" . | nindent 4 }}
spec:
  type: {{ .Values.servicea.service.type }}
  ports:
    - port: {{ .Values.servicea.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "servicea.selectorLabels" . | nindent 4 }}