apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servicea.fullname" . }}
  labels:
    {{- include "servicea.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "servicea.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.servicea.podAnnotations -}}  
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "servicea.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.servicea.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "servicea.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.servicea.podSecurityContext | nindent 8 }}
      containers:
        - name: servicea
          securityContext:
            {{- toYaml .Values.servicea.securityContext | nindent 12 }}
          image: "{{ .Values.servicea.image.repository }}:{{ .Values.servicea.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.servicea.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10  
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30   
          resources:
            {{- toYaml .Values.servicea.resources | nindent 12 }}
      {{- with .Values.servicea.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.servicea.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.servicea.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
